import Link from "next/link";
import { Copy, ExternalLink, Plus } from "lucide-react";
import { PageHeader, PaymentRuleBanner } from "@/components/brand";
import { EmptyState, Button, Card, Table } from "@/components/ui";
import { StatsCard, StatusBadge } from "@/components/dashboard";
import { createClient } from "@/lib/supabase/server";

const titles: Record<string, [string, string]> = { profile: ["Mijn profiel", "Houd uw bedrijfs- en contactgegevens actueel."], verification: ["Identiteitsverificatie", "Voltooi de verificatie voordat u actief verkoopt."], agreement: ["Partnerovereenkomst", "Bekijk en accepteer uw partnervoorwaarden."], products: ["Producten", "Beschikbare VDB-producten voor uw verkoopkanaal."], sales: ["Verkopen", "Alle door u geregistreerde verkopen."], commissions: ["Commissies", "Commissies worden alleen vrijgegeven na betaling en levering."], payouts: ["Uitbetalingen", "Uitbetalingen naar uw geverifieerde rekening."], marketing: ["Marketingmateriaal", "Gebruik uitsluitend goedgekeurde VDB-materialen."], referrals: ["Verwijzingen", "Partners die via uw introductie zijn aangemeld."], notifications: ["Meldingen", "Belangrijke updates over uw account en verkopen."], support: ["Support", "Neem contact op met VDB Partner Support."], settings: ["Instellingen", "Beheer uw portal- en notificatievoorkeuren."] };
async function sellerSummary() { try { const db = await createClient(); const { data: { user } } = await db.auth.getUser(); if (!user) return null; const { data: seller } = await db.from("seller_profiles").select("id").eq("user_id", user.id).maybeSingle(); if (!seller) return { sales: 0, commissions: 0, email: user.email }; const [{ count: sales }, { count: commissions }] = await Promise.all([db.from("orders").select("*", { count: "exact", head: true }).eq("seller_id", seller.id), db.from("commissions").select("*", { count: "exact", head: true }).eq("seller_id", seller.id)]); return { sales: sales ?? 0, commissions: commissions ?? 0, email: user.email }; } catch { return null; } }
export default async function SellerPage({ params }: { params: Promise<{ section?: string[] }> }) {
  const { section = [] } = await params; const slug = section[0]; const isDetail = section.length > 1; const summary = await sellerSummary();
  if (!slug) return <><PageHeader eyebrow="Partner Portal" title={`Goedendag${summary?.email ? "," : ""}`} description={summary?.email ? `Ingelogd als ${summary.email}` : "Verbind uw account met Supabase om uw actuele gegevens te laden."} actions={<StatusBadge status="in_review" />} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatsCard label="Verkopen" value={String(summary?.sales ?? 0)} detail="Geregistreerd" /><StatsCard label="Commissies" value={String(summary?.commissions ?? 0)} detail="Nog niet uitgekeerd" /><StatsCard label="Beschikbaar" value="€ 0,00" detail="Na vrijgave" /><StatsCard label="Uitbetaald" value="€ 0,00" detail="Historisch" /></div><div className="mt-7 grid gap-6 lg:grid-cols-2"><Card className="p-6"><p className="text-xs uppercase tracking-[.16em] text-gold">Uw partnercode</p><p className="display mt-2 text-3xl">—</p><p className="mt-2 text-sm text-muted">Uw code wordt zichtbaar na goedkeuring.</p></Card><Card className="p-6"><p className="text-xs uppercase tracking-[.16em] text-gold">Uw partnerlink</p><div className="mt-4 flex gap-2"><code className="flex-1 truncate rounded-sm border bg-black/20 p-2 text-xs text-muted">Beschikbaar na goedkeuring</code><Button variant="outline" size="sm" disabled><Copy className="h-4 w-4" /></Button></div><div className="mt-5 flex h-24 w-24 items-center justify-center border border-dashed text-[10px] text-muted">QR volgt</div></Card></div><PaymentRuleBanner className="mt-7" /></>;
  const [title, description] = titles[slug] ?? ["Details", "Bekijk de gegevens van dit onderdeel."];
  const newSale = slug === "sales" && !isDetail;
  return <><PageHeader title={newSale && section[1] === "new" ? "Nieuwe verkoop" : title} description={description} actions={newSale ? <Link href="/dashboard/sales/new"><Button><Plus className="mr-2 h-4 w-4" />Nieuwe verkoop</Button></Link> : undefined} />{slug === "sales" && section[1] === "new" ? <Card className="max-w-2xl p-6"><p className="mb-5 text-sm text-muted">Registreer een verkoop. U kunt geen betaling of commissie bevestigen; dat gebeurt uitsluitend door VDB.</p><form className="grid gap-4"><input className="h-10 rounded-sm border bg-black/20 px-3" placeholder="Klantnaam" /><input className="h-10 rounded-sm border bg-black/20 px-3" placeholder="E-mailadres klant" /><textarea className="min-h-24 rounded-sm border bg-black/20 p-3" placeholder="Opmerkingen" /><Button>Verkoop indienen</Button></form></Card> : <EmptyState title={isDetail ? "Record niet gevonden" : `Nog geen ${title.toLowerCase()}`} description="Koppel de database om live gegevens te laden. Statussen worden nooit als betaald weergegeven zonder verificatie." action={slug === "support" ? <Button variant="outline">Supportverzoek starten</Button> : undefined} />}{slug === "products" && <Card className="mt-6 p-5"><Table><thead><tr className="border-b text-xs text-muted"><th className="pb-3">Product</th><th className="pb-3">Status</th><th className="pb-3">Actie</th></tr></thead><tbody><tr><td className="py-4">Productcatalogus wordt geladen na configuratie.</td><td><StatusBadge status="pending" /></td><td><ExternalLink className="h-4 w-4 text-gold" /></td></tr></tbody></Table></Card>}</>;
}
