import Link from "next/link";
import { Copy, ExternalLink, Plus } from "lucide-react";
import { PageHeader, PaymentRuleBanner } from "@/components/brand";
import { SellerSaleForm } from "@/components/portal/seller-sale-form";
import { EmptyState, Button, Card, Table } from "@/components/ui";
import { StatsCard, StatusBadge } from "@/components/dashboard";
import { requireRole } from "@/lib/auth/require-auth";
import { createAdminClient } from "@/lib/supabase/admin";

const titles: Record<string, [string, string]> = { profile: ["Mijn profiel", "Houd uw bedrijfs- en contactgegevens actueel."], verification: ["Identiteitsverificatie", "Voltooi de verificatie voordat u actief verkoopt."], agreement: ["Partnerovereenkomst", "Bekijk en accepteer uw partnervoorwaarden."], products: ["Producten", "Beschikbare VDB-producten voor uw verkoopkanaal."], sales: ["Verkopen", "Alle door u geregistreerde verkopen."], commissions: ["Commissies", "Commissies worden alleen vrijgegeven na betaling en levering."], payouts: ["Uitbetalingen", "Uitbetalingen naar uw geverifieerde rekening."], marketing: ["Marketingmateriaal", "Gebruik uitsluitend goedgekeurde VDB-materialen."], referrals: ["Verwijzingen", "Partners die via uw introductie zijn aangemeld."], notifications: ["Meldingen", "Belangrijke updates over uw account en verkopen."], support: ["Support", "Neem contact op met VDB Partner Support."], settings: ["Instellingen", "Beheer uw portal- en notificatievoorkeuren."] };
async function sellerSummary(userId: string, email: string | null) { const db = createAdminClient(); const { data: seller, error } = await db.from("seller_profiles").select("id").eq("user_id", userId).maybeSingle(); if (error) throw error; if (!seller) return { sales: 0, commissions: 0, email, sellerId: null }; const [{ count: sales }, { count: commissions }] = await Promise.all([db.from("orders").select("*", { count: "exact", head: true }).eq("seller_id", seller.id), db.from("commissions").select("*", { count: "exact", head: true }).eq("seller_id", seller.id)]); return { sales: sales ?? 0, commissions: commissions ?? 0, email, sellerId: seller.id }; }
export default async function SellerPage({ params }: { params: Promise<{ section?: string[] }> }) {
  const profile = await requireRole("seller");
  const { section = [] } = await params; const slug = section[0]; const isDetail = section.length > 1; const summary = await sellerSummary(profile.id, profile.email);
  if (!slug) return <><PageHeader eyebrow="Partner Portal" title={`Goedendag${summary?.email ? "," : ""}`} description={summary?.email ? `Ingelogd als ${summary.email}` : "Verbind uw account met Supabase om uw actuele gegevens te laden."} actions={<StatusBadge status="in_review" />} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatsCard label="Verkopen" value={String(summary?.sales ?? 0)} detail="Geregistreerd" /><StatsCard label="Commissies" value={String(summary?.commissions ?? 0)} detail="Nog niet uitgekeerd" /><StatsCard label="Beschikbaar" value="€ 0,00" detail="Na vrijgave" /><StatsCard label="Uitbetaald" value="€ 0,00" detail="Historisch" /></div><div className="mt-7 grid gap-6 lg:grid-cols-2"><Card className="p-6"><p className="text-xs uppercase tracking-[.16em] text-gold">Uw partnercode</p><p className="display mt-2 text-3xl">—</p><p className="mt-2 text-sm text-muted">Uw code wordt zichtbaar na goedkeuring.</p></Card><Card className="p-6"><p className="text-xs uppercase tracking-[.16em] text-gold">Uw partnerlink</p><div className="mt-4 flex gap-2"><code className="flex-1 truncate rounded-sm border bg-black/20 p-2 text-xs text-muted">Beschikbaar na goedkeuring</code><Button variant="outline" size="sm" disabled><Copy className="h-4 w-4" /></Button></div><div className="mt-5 flex h-24 w-24 items-center justify-center border border-dashed text-[10px] text-muted">QR volgt</div></Card></div><PaymentRuleBanner className="mt-7" /></>;
  const [title, description] = titles[slug] ?? ["Details", "Bekijk de gegevens van dit onderdeel."];
  const newSale = slug === "sales" && !isDetail;
  if (slug === "sales" && section[1] === "new") return <><PageHeader title="Nieuwe verkoop" description="Registreer een verkoop. Betaling en commissie worden uitsluitend door VDB bevestigd." /><Card className="max-w-2xl p-6"><SellerSaleForm /></Card><PaymentRuleBanner className="mt-6" /></>;
  if (slug === "commissions") {
    const { data: commissions, error } = await createAdminClient().from("commissions").select("id, commission_number, status, amount_cents, currency, available_at, paid_at, created_at").eq("seller_id", summary.sellerId ?? "").order("created_at", { ascending: false });
    if (error) throw error;
    return <><PageHeader title={title} description={description} /><PaymentRuleBanner className="mb-6" />{commissions?.length ? <Card className="p-6"><Table><thead><tr className="border-b text-xs text-muted"><th className="pb-3">Commissie</th><th className="pb-3">Status</th><th className="pb-3">Bedrag</th><th className="pb-3">Beschikbaar</th></tr></thead><tbody>{commissions.map((commission) => <tr key={commission.id} className="border-b border-border/50" data-testid={`commission-row-${commission.id}`}><td className="py-4">{commission.commission_number}</td><td className="py-4" data-testid={`commission-status-${commission.id}`}><StatusBadge status={commission.status} /></td><td className="py-4">{new Intl.NumberFormat("nl-NL", { style: "currency", currency: commission.currency }).format(commission.amount_cents / 100)}</td><td className="py-4 text-muted">{commission.paid_at ? "Uitbetaald" : commission.available_at ? new Date(commission.available_at).toLocaleDateString("nl-NL") : "Nog niet beschikbaar"}</td></tr>)}</tbody></Table></Card> : <EmptyState title="Nog geen commissies" description="Commissies worden zichtbaar na geverifieerde betaling en levering." />}</>;
  }
  return <><PageHeader title={title} description={description} actions={newSale ? <Link href="/dashboard/sales/new"><Button><Plus className="mr-2 h-4 w-4" />Nieuwe verkoop</Button></Link> : undefined} /><EmptyState title={isDetail ? "Record niet gevonden" : `Nog geen ${title.toLowerCase()}`} description="Statussen worden nooit als betaald weergegeven zonder verificatie." action={slug === "support" ? <Button variant="outline">Supportverzoek starten</Button> : undefined} />{slug === "products" && <Card className="mt-6 p-5"><Table><thead><tr className="border-b text-xs text-muted"><th className="pb-3">Product</th><th className="pb-3">Status</th><th className="pb-3">Actie</th></tr></thead><tbody><tr><td className="py-4">Productcatalogus wordt geladen na configuratie.</td><td><StatusBadge status="pending" /></td><td><ExternalLink className="h-4 w-4 text-gold" /></td></tr></tbody></Table></Card>}</>;
}
