import { PageHeader } from "@/components/brand";
import { Card, EmptyState, Table } from "@/components/ui";
import { StatsCard, StatusBadge } from "@/components/dashboard";
import { createAdminClient } from "@/lib/supabase/admin";

const names: Record<string, [string, string]> = { sellers: ["Partners", "Beheer partnerprofielen en goedkeuringen."], applications: ["Aanmeldingen", "Nieuwe partneraanmeldingen ter beoordeling."], verifications: ["Verificaties", "Identiteitscontroles en uitzonderingen."], agreements: ["Overeenkomsten", "Status van partnerovereenkomsten."], products: ["Producten", "Productcatalogus en commissietarieven."], orders: ["Orders", "Orders en leveringsstatussen."], payments: ["Betalingen", "Betalingen alleen bevestigd via VDB of Mollie."], commissions: ["Commissies", "Vrijgave na geverifieerde betaling en levering."], "commission-rules": ["Commissieregels", "Regels per product en partner."], payouts: ["Uitbetalingen", "Uitbetalingen en batches."], refunds: ["Refunds", "Refunds met impact op commissies."], disputes: ["Geschillen", "Openstaande partner- of klantgeschillen."], reports: ["Rapporten", "Financiële en operationele rapporten."], audit: ["Auditlog", "Onwijzigbare gebeurtenissen en beheerdersacties."], settings: ["Instellingen", "Portalconfiguratie."], team: ["Team", "Beheerders en rollen."] };
async function metrics() { try { const db = createAdminClient(); const [orders, sellers, payouts] = await Promise.all([db.from("orders").select("*", { count: "exact", head: true }), db.from("profiles").select("*", { count: "exact", head: true }).eq("role", "seller"), db.from("payouts").select("*", { count: "exact", head: true })]); return { orders: orders.count ?? 0, sellers: sellers.count ?? 0, payouts: payouts.count ?? 0 }; } catch { return null; } }
export default async function AdminPage({ params }: { params: Promise<{ section?: string[] }> }) {
  const { section = [] } = await params; const slug = section[0]; const stats = await metrics();
  if (!slug) return <><PageHeader eyebrow="Eigenaar" title="Command center" description={stats ? "Actuele gegevens uit de beheerdatabase." : "Verbind de Supabase service-role om live beheergegevens te laden."} /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatsCard label="Orders" value={String(stats?.orders ?? 0)} detail="Totaal geregistreerd" /><StatsCard label="Partners" value={String(stats?.sellers ?? 0)} detail="Totaal" /><StatsCard label="Uitbetalingen" value={String(stats?.payouts ?? 0)} detail="Geregistreerd" /><StatsCard label="Omzet" value="€ —" detail="Beschikbaar na koppeling" /></div><Card className="mt-7 p-6"><p className="text-xs uppercase tracking-[.16em] text-gold">Controlepunten</p><div className="mt-4 grid gap-3 md:grid-cols-3"><div><StatusBadge status="pending" /><p className="mt-2 text-sm text-muted">Partners in review</p></div><div><StatusBadge status="pending" /><p className="mt-2 text-sm text-muted">Betalingen te verifiëren</p></div><div><StatusBadge status="pending" /><p className="mt-2 text-sm text-muted">Payouts in behandeling</p></div></div></Card></>;
  const [title, description] = names[slug] ?? ["Details", "Beheer de gegevens van dit onderdeel."];
  return <><PageHeader eyebrow={section.length > 1 ? "Detail" : "Beheer"} title={title} description={description} />{slug === "payments" && <Card className="mb-6 p-5 text-sm text-[#e5d3b0]">Betaalstatussen mogen uitsluitend door Mollie-webhooks of bevoegde VDB-beheerders worden bevestigd.</Card>}<EmptyState title={section.length > 1 ? "Record niet gevonden" : `Geen ${title.toLowerCase()}`} description="Er zijn nog geen records beschikbaar, of de beheerdatabase is niet geconfigureerd." />{["orders", "sellers", "products", "payouts"].includes(slug) && <Card className="mt-6 p-5"><Table><thead><tr className="border-b text-xs text-muted"><th className="pb-3">Referentie</th><th className="pb-3">Status</th><th className="pb-3">Bijgewerkt</th></tr></thead><tbody><tr><td className="py-4">Geen records geladen</td><td><StatusBadge status="pending" /></td><td className="text-muted">—</td></tr></tbody></Table></Card>}</>;
}
